import { CORE_PACKAGES } from './CORE_PACKAGES.js';

export const ALL_CORE_PACKAGES = [
  // FP Packages
  CORE_PACKAGES.FP.OPTION,
  CORE_PACKAGES.FP.OPTION_SHARED,
  CORE_PACKAGES.FP.RESULT,
  CORE_PACKAGES.FP.RESULT_SHARED,
  CORE_PACKAGES.FP.UNION,
  CORE_PACKAGES.FP.UNION_SHARED,

  // DS Packages
  CORE_PACKAGES.DS.COLLECTION,
  CORE_PACKAGES.DS.COLLECTION_SHARED,
  CORE_PACKAGES.DS.TREE,
  CORE_PACKAGES.DS.TREE_SHARED,

  // Utils Packages
  CORE_PACKAGES.UTILS.MATCHING,
  CORE_PACKAGES.UTILS.VALIDATION,
  CORE_PACKAGES.UTILS.SERIALIZATION,
] as const;
