import { CORE_PACKAGES } from './CORE_PACKAGES.js';

export const CONTEXT_DEPENDENCIES = {
  FP: [
    CORE_PACKAGES.FP.OPTION,
    CORE_PACKAGES.FP.RESULT,
    CORE_PACKAGES.FP.UNION,
  ] as const,

  FP_TYPES: [
    CORE_PACKAGES.FP.OPTION_SHARED,
    CORE_PACKAGES.FP.RESULT_SHARED,
    CORE_PACKAGES.FP.UNION_SHARED,
  ] as const,

  DS: [CORE_PACKAGES.DS.COLLECTION, CORE_PACKAGES.DS.TREE] as const,

  DS_TYPES: [
    CORE_PACKAGES.DS.COLLECTION_SHARED,
    CORE_PACKAGES.DS.TREE_SHARED,
  ] as const,
} as const;
