import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/introduction/01-overview',
        'introduction/introduction/02-installation',
        'introduction/introduction/03-quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/basic-usage', 'guides/index'],
    },
    {
      type: 'category',
      label: 'Patterns',
      items: ['patterns/index'],
    },
    {
      type: 'category',
      label: 'Examples',
      items: [
        'examples/quick-start/00-quick-start',
        'examples/quick-start/hello-world/example',
        'examples/quick-start/basic-usage/example',
        'examples/quick-start/error-handling/example',
        'examples/quick-start/chaining/example',
        'examples/api-reference/01-api-reference',
        'examples/api-reference/constructors/ok/basic-usage/example',
        'examples/api-reference/constructors/ok/with-generics/example',
        'examples/api-reference/constructors/ok/real-world/example',
        'examples/api-reference/constructors/err/basic-usage/example',
        'examples/api-reference/constructors/err/with-custom-error/example',
        'examples/api-reference/constructors/err/real-world/example',
        'examples/api-reference/guards/is-ok/basic-usage/example',
        'examples/api-reference/guards/is-err/basic-usage/example',
        'examples/api-reference/guards/is-ok-and/basic-usage/example',
        'examples/api-reference/guards/is-err-and/basic-usage/example',
        'examples/api-reference/methods/transformation/map/basic-usage/example',
        'examples/api-reference/methods/transformation/map-err/basic-usage/example',
        'examples/api-reference/methods/chaining/and-then/basic-usage/example',
        'examples/api-reference/methods/chaining/or-else/basic-usage/example',
        'examples/api-reference/methods/extraction/unwrap/basic-usage/example',
        'examples/api-reference/methods/extraction/unwrap-or/basic/example',
        'examples/api-reference/methods/extraction/expect/basic/example',
        'examples/api-reference/methods/extraction/unwrap-err/basic/example',
        'examples/api-reference/methods/extraction/expect-err/basic/example',
        'examples/api-reference/methods/extraction/unwrap-or-else/basic/example',
        'examples/api-reference/methods/side-effects/tap/basic-usage/example',
        'examples/api-reference/methods/side-effects/tap-err/basic/example',
        'examples/api-reference/methods/side-effects/inspect/basic/example',
        'examples/api-reference/methods/side-effects/inspect-err/basic/example',
        'examples/api-reference/methods/advanced/match/basic-usage/example',
        'examples/api-reference/methods/advanced/flatten/basic/example',
        'examples/api-reference/methods/advanced/transpose/basic/example',
        'examples/api-reference/methods/advanced/ok/basic/example',
        'examples/api-reference/methods/advanced/err/basic/example',
        'examples/api-reference/refiners/is-typed-variant/basic-usage/example',
        'examples/api-reference/refiners/is-typed-variant-of/basic/example',
        'examples/api-reference/refiners/match-variant/basic/example',
        'examples/api-reference/refiners/match-variant-strict/basic/example',
        'examples/api-reference/refiners/refine-result/basic/example',
        'examples/api-reference/refiners/refine-result-u/basic/example',
        'examples/api-reference/refiners/refine-async-result/basic/example',
        'examples/api-reference/refiners/refine-async-result-u/basic/example',
        'examples/api-reference/refiners/refine-variant-map/basic/example',
        'examples/patterns/02-patterns',
        'examples/patterns/async/basics/example',
        'examples/patterns/async/concurrent/example',
        'examples/patterns/async/streams/example',
        'examples/patterns/http/api-client/example',
        'examples/patterns/http/web-scraping/example',
        'examples/patterns/validation/validation/example',
        'examples/patterns/error-handling/error-recovery/example',
        'examples/patterns/events/event-handling/example',
        'examples/patterns/workers/worker-pool/example',
      ],
    },
  ],
};

export default sidebars;
